-- MySQL Script generated by MySQL Workbench
-- Fri Jul  1 16:50:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema koalify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema koalify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `koalify` DEFAULT CHARACTER SET latin1 ;
USE `koalify` ;

-- -----------------------------------------------------
-- Table `koalify`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koalify`.`categories` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `accent_color` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `koalify`.`challenges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koalify`.`challenges` (
  `id` INT NOT NULL,
  `category_id` INT(11) NOT NULL,
  `title` VARCHAR(45) NULL,
  `brief` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_challenges_categories_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_challenges_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `koalify`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koalify`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koalify`.`questions` (
  `id` INT NOT NULL,
  `challenge_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `type` ENUM('PRACTICAL', 'THEORICAL') NULL,
  `level` ENUM('EASY', 'MEDIUM', 'HARD') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_challenges1_idx` (`challenge_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_challenges1`
    FOREIGN KEY (`challenge_id`)
    REFERENCES `koalify`.`challenges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koalify`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koalify`.`answers` (
  `id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `value` VARCHAR(45) NULL,
  `correctAnswer` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answers_questions1_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`question_id`)
    REFERENCES `koalify`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
